SEED: 42
DEVICE: "cuda"

LOGGING:
  WANDB: false
  PROJECT_NAME: "decathlon"
  TRAIN_NAME: "decathlon_mednca"
  LOG_INTERVAL: 100
  SAVE_INTERVAL: 2000
  INTERMEDIATE_LOGGING_STEPS: [5, 10, 15]

MODEL:
  NAME: "NoBiasMLP"
  HIDDEN_CHANNELS: [128]
  CHANNEL_N: 32
  USE_POSITIONAL_EMBEDDINGS: false
  LIVING_MASK: false
  CLAMP_OUTPUT: false
  FINAL_ACTIVATION: false
  FIRE_RATE: 0.5
  PERCEPTIONS:
    - MODE: "identity_conv"
      KERNEL_SIZE: 3
      OUT_CHANNEL: 96

TRAINING:
  TRAINER_TYPE: "med_nca"
  BATCH_SIZE: 48
  STEPS: 100000
  LEARNING_RATE: 0.0016
  LR_SCHEDULE_MODE: "exponential"
  LR_GAMMA: 0.9999
  OPTIMIZER_BETAS: [0.5, 0.5]
  WARMUP_STEPS: 0
  LOSS_FN: "dice_bce"
  OVERFLOW_LOSS: false
  ITER_N_MIN: 64
  ITER_N_MAX: 64

  GRADIENT_CLIPPING_NORM: 1.0
  GRADIENT_CHECKPOINTING: false
  GRADIENT_ACCUMULATION_STEPS: 1

DATASET:
  NAME: "decathlon"
  TARGET_SIZE: 256
  DATAROOT: "/content/drive/MyDrive/Task04_Hippocampus"
  NUM_WORKERS: 2

PATTERN_POOL:
  ENABLED: false
