SEED: 42                                  # Random seed
DEVICE: "cuda"                             # Device to use for training
MODEL:
  NAME: "MLP"
  HIDDEN_CHANNELS: [80]
  CHANNEL_N: 16
  USE_POSITIONAL_EMBEDDINGS: False
  LIVING_MASK: true
  CLAMP_OUTPUT: false
  FINAL_ACTIVATION: false
  PERCEPTIONS:
    - MODE: "depthwise_separable_conv"
      KERNEL_SIZE: 3


TRAINING:
  BATCH_SIZE: 18
  STEPS: 100000
  LEARNING_RATE: 0.0005
  LR_SCHEDULE_MODE: "cosine"
  LOSS_FN: "mse"
  WARMUP_STEPS: 5000
  OVERFLOW_LOSS: true
  LR_GAMMA: 0.1
  ITER_N_MIN: 48
  ITER_N_MAX: 64
  GRADIENT_CLIPPING_NORM: 1.0
  GRADIENT_CHECKPOINTING: false
  GRADIENT_CHECKPOINT_SEGMENTS: 10
  GRADIENT_ACCUMULATION_STEPS: 1

DATASET:
  NAME: "emoji"                            # Name of the dataset [emoji, e2h, mnist]
  TARGET_SIZE: 48
  TARGET_PADDING: 16
  EMOJIS:
    - "😭"
    - "🔥"
    - "🎉"
    - "🍀"
    - "🍎"

PATTERN_POOL:
  ENABLED: true
  POOL_SIZE: 1024
  POOL_DELAY: 1
  POOL_START_RATIO: 0.5
  POOL_END_RATIO: 0.5
  POOL_DMG_RATIO: 0.5
  POOL_DMG_DELAY: 1
  POOL_MUTATION_RATIO: 0.5


LOGGING:
  WANDB: false
  PROJECT_NAME: "emoji"                 # Name of the project
  TRAIN_NAME: "emoji_dwsep3x3"              # Name of the training run
  LOG_INTERVAL: 500
  SAVE_INTERVAL: 25000
  INTERMEDIATE_LOGGING_STEPS: [5, 20, 40]
