SEED: 42
DEVICE: cuda
LOGGING:
  WANDB: false
  PROJECT_NAME: decathlon
  TRAIN_NAME: decathlon_mednca
  DEBUG: false
  LOG_INTERVAL: 100
  SAVE_INTERVAL: 2000
  INTERMEDIATE_LOGGING_STEPS:
  - 5
  - 10
  - 15
  OBSERVERS: []
MODEL:
  NAME: NoBiasMLP
  HIDDEN_CHANNELS:
  - 128
  CHANNEL_N: 32
  CHANNEL_OUT: 32
  USE_POSITIONAL_EMBEDDINGS: false
  LIVING_MASK: false
  LIVING_MASK_INDEX: 3
  NOISE_INJECTION: 0.0
  FINAL_ACTIVATION: false
  CLAMP_OUTPUT: false
  CLAMP_OUTPUT_MIN: -1.0
  CLAMP_OUTPUT_MAX: 1.0
  FIRE_RATE: 0.5
  RESNET_BLOCKS: 2
  PERCEPTIONS:
  - MODE: identity_conv
    KERNEL_SIZE: 3
    DILATION: 1
    OUT_CHANNEL: 96
    NUM_HEADS: 4
    EMBED_DIM: 128
    USE_REL_POS_BIAS: true
    USE_LAYER_NORM: true
    INCLUDE_FFN: true
TRAINING:
  BATCH_SIZE: 48
  STEPS: 100000
  LOSS_FN: dice_bce
  OVERFLOW_LOSS: false
  LEARNING_RATE: 0.0016
  WARMUP_STEPS: 0
  LR_SCHEDULE_MODE: exponential
  MILESTONES:
  - 2000
  - 8000
  LR_GAMMA: 0.9999
  OPTIMIZER_BETAS:
  - 0.5
  - 0.5
  ITER_N_MIN: 64
  ITER_N_MAX: 64
  GRADIENT_CLIPPING_NORM: 1.0
  GRADIENT_CHECKPOINTING: false
  GRADIENT_CHECKPOINT_SEGMENTS: 16
  GRADIENT_ACCUMULATION_STEPS: 1
  MIXED_PRECISION: false
  OVERFLOW_WEIGHT: 1.0
  LPIPS_NET: alex
  VGG_PROJ_N: 32
  TRAINER_TYPE: med_nca
  EVOLVE_MODE: base
  WSD_DECAY_RATIO: 0.1
  WSD_MIN_LR_RATIO: 0.0
DATASET:
  NAME: decathlon
  DATAROOT: /content/drive/MyDrive/Task04_Hippocampus
  DROP_LAST_BATCH: true
  TARGET_SIZE: 256
  TARGET_PADDING: 0
  EMOJIS: []
  HISTORY_N: 1
  REVERSE_HISTORY_SEED: false
  NUM_WORKERS: 2
  SEED_SIZE: 1
  ENABLE_ROTATION: false
  ENABLE_ZOOM: false
  Z_LATENT_NOISE_CHANNEL: false
CFG:
  ENABLED: false
  DROPOUT_PROB: 0.1
  NULL_CONDITION_TYPE: zeros
  GOAL_CHANNELS: false
  PRESERVE_CHANNELS: []
PATTERN_POOL:
  ENABLED: false
  TIMESERIES_POOL: false
  POOL_SIZE: 1024
  POOL_DELAY: 1000
  POOL_START_RATIO: 0.5
  POOL_END_RATIO: 0.5
  POOL_DMG_RATIO: 0.0
  POOL_MUTATION_RATIO: 0.0
LATENT_TRAINING:
  ENABLED: false
  ENCODER_TYPE: AE
  LATENT_AE_STEPS: 10000
  LATENT_AE_WARMUP_STEPS: 2000
  LATENT_AE_LR: 0.001
  LATENT_AE_IN_CHANNEL: 4
  LATENT_AE_OUT_CHANNEL: 4
  LATENT_AE_CHANNEL: 64
  LATENT_AE_COMPRESSION: 3
  LATENT_AE_LOG_INTERVAL: 2500
  LATENT_AE_SAVE_INTERVAL: 5000
  APPLY_DAMAGE: false
  VAE_KL_BETA: 1.0
  VAE_BASE_CHANNELS: 64
  VAE_NUM_DOWNSAMPLES: 5
  VAE_NORM_GROUPS: 32
  VAE_KL_WARMUP_STEPS: 0
  VAE_BATCH_SIZE: 18
  VAE_RECON_LOSS_TYPE: l1
  VAE_RECON_LOSS_WEIGHT: 1.0
  VAE_VGG_LOSS_WEIGHT: 1.0
  VQVAE_NUM_EMBEDDINGS: 512
  VQVAE_COMMITMENT_COST: 0.25
ADVERSARIAL:
  ENABLED: false
  D_IN_CHANNELS: 4
  D_FEATURES:
  - 64
  - 128
  - 256
  - 512
  D_LEARNING_RATE: 0.001
  D_START_TRAINING: 0
  D_WARMUP_STEPS: 0
  D_GAMMA: 0.1
  D_N_CRITIC: 1
  D_GP_WEIGHT: 10.0
  D_DOWNSCALE_FACTOR: 1
  LPIPS_WEIGHT: 0.0
  ADV_WEIGHT: 1.0
  RECON_WEIGHT: 1.0
  SEED_TO_CRITIC: false
TORCH_COMPILE:
  ENABLED: false
  MODE: default
  DEBUG: false
COND_DIM: 0
IM_HEIGHT: 256
IM_WIDTH: 256
